version: '3.8'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    network_mode: 'bridge'
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest_api
    network_mode: 'bridge'
